feat: add email commands
FusionAuth/fusionauth-node-cli pull request #4
Opened 2023-07-11 12:01 UTC by ColinFrick

This PR adds the following email commands:
- `fusionauth email:create` - Create a new email template locally.
- `fusionauth email:download` - Download a specific template or all email templates from a FusionAuth server.
- `fusionauth email:duplicate` - Duplicate an email template locally.
- `fusionauth email:html-to-text` - Convert HTML email templates to text, where the text template is missing.
- `fusionauth email:upload` - Upload a specific template or all email templates to a FusionAuth server.
- `fusionauth email:watch` - Watch the email template directory and upload changes to a FusionAuth server.

The email directory is as follows:
```
emails
├── 004e5f2e-ec50-4eda-998e-c58afd2a048d
│   ├── body.html
│   ├── body.txt
│   ├── from_email.txt
│   ├── from_name.txt
│   ├── fuubar.txt
│   ├── name.txt
│   └── subject.txt
├── 530100f3-e25b-49e3-bdd0-46e4c2f06b9e
│   ├── de
│   │   ├── body.html
│   │   ├── body.txt
│   │   ├── from_name.txt
│   │   └── subject.txt
│   ├── fr
│   │   ├── body.html
│   │   ├── body.txt
│   │   ├── from_name.txt
│   │   └── subject.txt
│   ├── body.html
│   ├── body.txt
│   ├── from_email.txt
│   ├── from_name.txt
│   ├── name.txt
│   └── subject.txt
```

So we have a directory for each template containing the base properties and default templates. Locales are subdirectory containing the localized templates.

Closes #2

2023-07-26 14:38 UTC, mooreds commented
@vcampitelli did you have a chance to look at this?

2023-07-26 16:19 UTC, vcampitelli requested changes
Just a few nitpicks. Great work though!

2023-07-26 16:19 UTC, vcampitelli commented on src/commands/email-download.ts
> +import * as fs from "fs";
```suggestion
import {existsSync} from "fs";
```

2023-07-26 16:19 UTC, vcampitelli commented on src/commands/email-download.ts
> +                if (!fs.existsSync(emailTemplateDirectory)) {
```suggestion
                if (!existsSync(emailTemplateDirectory)) {
```

2023-07-26 16:19 UTC, vcampitelli commented on src/commands/email-download.ts
> +                    if (!fs.existsSync(localeDirectory)) {
```suggestion
                    if (!existsSync(localeDirectory)) {
```

2023-07-26 16:19 UTC, vcampitelli commented on src/commands/email-download.ts
> +export const getLocalesFromEmailTemplates = (emailTemplate: EmailTemplate): string[] => {
Nice :sunglasses:

2023-08-08 11:17 UTC, mooreds commented
@vcampitelli can you take another look, please?

2023-08-08 13:05 UTC, vcampitelli commented
I pushed f1a38d94278af88ec41b8592a03947faa5ae761b to remove an `export` because the script was trying to add it as a command and it's just a helper function.

```
src/index.ts:23:63 - error TS2345: Argument of type 'Command<[], { output: string; locales: [] | string[]; }> | Command<[string | undefined], { output: string; }> | Command<[string | undefined], { output: string; key: string; host: string; clean: boolean; }> | ... 8 more ... | Command<...>' is not assignable to parameter of type 'CommandUnknownOpts'.
  Type '(emailTemplate: EmailTemplate) => string[]' is not assignable to type 'Command<unknown[], OptionValues>'.

23 Object.values(commands).forEach(command => program.addCommand(command));
```                                                                 ~~~~~~~

2023-08-08 13:05 UTC, vcampitelli approved these changes

2023-08-08 14:09 UTC, merged