Added commands to retrieve, update and delete a Lambda
FusionAuth/fusionauth-node-cli pull request #5
Opened 2023-07-14 11:02 UTC by rideam

2023-07-17 10:10 UTC, ColinFrick requested changes
Thanks for the PR @rideam 

There are some unused imports in `lambda-delete.ts` and `lambda-update.ts`. Could you clean them up?

2023-07-17 10:10 UTC, ColinFrick commented on tsconfig.json
> +    "allowJs": true,                                     /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get errors from these files. */
Is this change necessary?

2023-07-17 10:10 UTC, ColinFrick commented on src/utils.ts
> +function errorIfFalse(value:  Object | undefined, message: string) {
Could you change the method name to `errorIfFalsy`?

IMHO `errorIfFalse` indicates a strict check on `false`.

2023-07-17 10:10 UTC, ColinFrick commented on package.json
> +    "start": "npx ts-node --esm src/index.ts",
Is `npx` required?

Node.js should call the locally installed packages (through `devDependencies`) first, so - if they are installed - global packages should not be called.

2023-07-17 10:10 UTC, ColinFrick commented on package.json
> +    "setVersionNumber": "sed -i \"s/versionfrompackagejson/$(jq -r .version package.json)/g\" ./dist/index.js"
I'm unable to build `node-cli` on MacOS:

![image](https://github.com/FusionAuth/fusionauth-node-cli/assets/5517677/77d2ab7e-0f62-45f6-8b74-2906e9a2b8e0)

Additionally `sed`, `chmod` and `jq` are not cross-platform. We either need to add these commands to the requirements for Dev, or use a cross-platform solution like:
```json
    "setVersionNumber": "cross-env replace-in-file versionfrompackagejson $npm_package_version ./dist/index.js"
```
Uses [cross-env](https://www.npmjs.com/package/cross-env) and [replace-in-file](https://www.npmjs.com/package/replace-in-file)

2023-07-17 10:10 UTC, ColinFrick commented on package.json
> +    "makeIndexJsExecutable": "chmod +x ./dist/index.js",
Seems only necessary if calling `index.js` directly. Will fail when building on Windows.

2023-07-19 09:54 UTC, sixhobbits commented
@ColinFrick - thanks for the feedback - we've implemented the changes. Let me know if you have any more feedback. We'll open a PR to the docs that includes a guide on how to use this new functionality soon.

2023-07-26 14:38 UTC, mooreds commented
@ColinFrick is this approved?

2023-07-31 09:38 UTC, ColinFrick approved these changes

2023-07-31 09:54 UTC, merged